#StackOverflow logo
import turtle
t = turtle.Turtle()
t.penup()
t.backward(350)
t.pendown()
t.speed(5)
t.color("#808080")
t.pensize(20)
t.right(90)
t.forward(100)
t.left(90)
t.forward(250)
t.left(90)
t.forward(100)
t.backward(20)
t.color("orange")
t.pensize(4)
t.left(90)
t.penup()
t.forward(25)
t.pendown()
for y in range(5):
    for i in range(2):
        t.begin_fill()
        t.forward(200)
        t.left(90)
        t.forward(25)
        t.left(90)
        t.end_fill()
    t.right(90)
    t.penup()
    t.forward(40)
    t.pendown()
    t.left(75)    
t.left(75)
t.right(90)
t.penup()
t.backward(350)
t.color("black")
t.write("overflow", move=False, align="left", font=("Century Gothic", 72, "bold"))
t.write("stack", move=False, align="right", font=("Century Gothic", 72, "normal"))
turtle.done()
