#Udemy logo
import turtle
t = turtle.Turtle()
t.speed(5)
t.color("purple")
t.pensize(20)
t.penup()
t.backward(350)
t.pendown()
t.left(30)
t.forward(87)
t.right(60)
t.forward(87)
t.right(30)
t.penup()
t.right(120)
t.forward(100)
t.left(90)
t.forward(180)
t.left(90)
t.forward(297)
t.color("black")
t.write("udemy", move=False, align="center", font=("Century Gothic", 144, "bold")) 
turtle.done()